pipeline {
  agent {
    kubernetes {
      label 'manage-composite-repository'
      defaultContainer 'jnlp'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: 'eclipsecbi/jenkins-jnlp-agent'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      limits:
        memory: "3.6Gi"
        cpu: "1.0"
      requests:
        memory: "3.6Gi"
        cpu: "1.0"
    volumeMounts:
    - mountPath: /home/jenkins/.ssh
      name: volume-known-hosts
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
    '''
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr:'15'))
    disableConcurrentBuilds()
    timeout(time: 15, unit: 'MINUTES')
    timestamps()
  }

  environment {
    DOWNLOAD_AREA = '/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates'
    TIMESTAMP = "${currentBuild.startTimeInMillis}"
  }

  parameters {
    choice(name: 'COMPOSITE_REPO_LOCATION', 
      choices: [
        'archive',
        'composite/archive',
        'composite/latest',
        'composite/maintenance/nightly',
        'composite/maintenance/releases',
        'composite/milestones',
        'composite/nightly',
        'composite/releases',
        'composite/staging',
        'epp',
        'milestones',
        'nightly',
        'orbit/maintenance',
        'orbit',
        'releases'
      ]
    )
    choice(
      name: 'OPERATION',
      choices: ['READ','ADD_LOCATION','REMOVE_LOCATION','CLEAR'],
      description: 'Action to perform with the composite repository.'
    )
    string(name: 'LOCATION_URL', description: 'For operation ADD_LOCATION, REMOVE_LOCATION: The URL to add or remove')
  }
  stages {
    stage('Download composite*.xml') {
      when {
        expression { env.COMPOSITE_REPO_LOCATION != null }
      }
      steps {
        script {
          currentBuild.description = "$COMPOSITE_REPO_LOCATION / $OPERATION"
        }
        sshagent(['projects-storage.eclipse.org-bot-ssh']) {
          sh '''
            #
            # Download compositeArtifacts.xml & compositeContent.xml from projects-storage
            #
            set -x

            scp genie.xtext@projects-storage.eclipse.org:$DOWNLOAD_AREA/$COMPOSITE_REPO_LOCATION/composite*.xml .
            
            cat compositeArtifacts.xml
            #cat compositeContent.xml

          '''
        }
      }
    }
    stage('Add Location') {
      when {
        allOf {
          expression {env.COMPOSITE_REPO_LOCATION != null }
          environment name: 'OPERATION', value: 'ADD_LOCATION'
          expression {env.LOCATION_URL != null }
        }
      }
      steps {
        sh '''
          #
          # Add given location to compositeArtifacts.xml & compositeContent.xml
          # and upload them back to projects-storage
          #
          set -x

        '''
      }
    }
    stage('Remove Location') {
      when {
        allOf {
          expression {env.COMPOSITE_REPO_LOCATION != null }
          environment name: 'OPERATION', value: 'REMOVE_LOCATION'
          expression {env.LOCATION_URL != null }
        }
      }
      steps {
        sh '''
          #
          # Remove given location from compositeArtifacts.xml & compositeContent.xml
          # and upload them back to projects-storage
          #
          set -x

        '''
      }
    }
  }
}
